# Generated by Django 4.2.4 on 2023-08-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_booth_number', models.CharField(blank=True, max_length=50, null=True)),
                ('polling_booth_name', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_constituency', models.CharField(blank=True, max_length=50, null=True)),
                ('winner2014', models.CharField(blank=True, max_length=50, null=True)),
                ('runner_up', models.CharField(blank=True, max_length=50, null=True)),
                ('margin1_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('margin1', models.CharField(blank=True, max_length=50, null=True)),
                ('total_voters', models.CharField(blank=True, max_length=50, null=True)),
                ('bjp1_votes', models.CharField(blank=True, max_length=50, null=True)),
                ('bjp1_vote_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('inc1_votes', models.CharField(blank=True, max_length=50, null=True)),
                ('inc1_votes_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('winner2019', models.CharField(blank=True, max_length=50, null=True)),
                ('margin2_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('margin2', models.CharField(blank=True, max_length=50, null=True)),
                ('total2_voters', models.CharField(blank=True, max_length=50, null=True)),
                ('bjp2_votes', models.CharField(blank=True, max_length=50, null=True)),
                ('bjp2_votes_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('inc2_votes', models.CharField(blank=True, max_length=50, null=True)),
                ('inc2_vote_percent', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
