# Generated by Django 4.2.4 on 2023-08-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
